export const universities = [
    {
        name: "Harvard University",
        rank: 1,
        country: "United States",
        scholars: 158,
        publications: 230,
        hIndex: 2000,
        logo: "https://1000logos.net/wp-content/uploads/2017/02/Harvard-Logo.png",
    },
    {
        name: "University of Cape Coast",
        rank: 2,
        country: "Ghana",
        scholars: 158,
        publications: 230,
        hIndex: 2000,
        logo: "https://ucc.edu.gh/sites/default/files/ucc-logo.webp",
    },
    {
        name: "Oxford University",
        rank: 3,
        country: "United Kingdom",
        scholars: 158,
        publications: 230,
        hIndex: 2000,
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-University-Circlet.svg/1636px-Oxford-University-Circlet.svg.png",
    },
    {
        name: "Princeton University",
        rank: 4,
        country: "United States",
        scholars: 158,
        publications: 230,
        hIndex: 2000,
        logo: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Princeton_seal.svg",
    },
    {
        name: "University of Cambridge",
        rank: 5,
        country: "United Kingdom",
        scholars: 158,
        publications: 230,
        hIndex: 2000,
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Coat_of_Arms_of_the_University_of_Cambridge.svg/180px-Coat_of_Arms_of_the_University_of_Cambridge.svg.png",
    }
]
